name: 🚀 Publish new version
# Run this on every push to master and next
on:
  push:
    branches:
      - master
      - next
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag name for RC release (e.g., rc, beta, alpha)"
        required: true
        type: string

env:
  HUSKY: 0

jobs:
  publish:
    # Use the latest version of Ubuntu
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      # Checkout repository
      - name: 📥 Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      # Setup PocketBase
      - name: 🗄️ Download and setup PocketBase
        id: setup-pocketbase
        background: true
        run: |
          # Download and setup PocketBase
          npm run test:e2e:setup

          # Start PocketBase in the background
          ./.pocketbase/pocketbase serve &

          # Wait for PocketBase to be ready
          until curl -s --fail http://localhost:8090/api/health; do
            echo 'Waiting for PocketBase...'
            sleep 5
          done

      # Setup Node
      - name: 📦 Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc

      # Enable corepack
      - name: ⚙️ Enable corepack
        run: corepack enable && corepack enable npm

      # Install dependencies
      - name: 📦 Install dependencies
        run: npm ci

      # Wait for PocketBase setup to complete
      - name: ⏳ Wait for PocketBase setup
        wait: [setup-pocketbase]

      - parallel:
          # Lint code
          - name: 🧹 Lint code (includes type-check)
            run: npm run lint

          # Check format
          - name: 🧹 Check format
            run: npm run format:check

          # Type check
          #   Still included for now, since the oxlint built-in typecheck uses TypeScript v7.
          #   This one uses the TypeScript version actually specified in the project.
          - name: 🧪 Type check
            run: npm run typecheck

          # Run tests
          - name: 🧪 Run tests
            run: npm run test

      # Create release
      - name: 🚀 Create release
        if: github.repository == 'pawcoding/astro-loader-pocketbase'
        id: release
        uses: cycjimmy/semantic-release-action@b12c8f6015dc215fe37bc154d4ad456dd3833c90 # v6.0.0
        with:
          semantic_version: 25
          extra_plugins: |
            conventional-changelog-conventionalcommits@9
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CUSTOM_TAG: ${{ inputs.tag }}

      # Update project on website
      - name: 🖥️ Update website
        if: github.repository == 'pawcoding/astro-loader-pocketbase' && steps.release.outputs.new_release_published == 'true' && !steps.release.outputs.new_release_channel  && steps.release.outputs.new_release_patch_version == '0'
        uses: pawcoding/update-project-action@763d90ef8cacf8ee7e2711290f99eb00abce519d # v0.1.0
        with:
          pocketbase-url: ${{ vars.PB_URL }}
          collection-id: ${{ vars.PB_COLLECTION }}
          record-id: ${{ vars.PB_RECORD }}
        env:
          PB_TOKEN: ${{ secrets.PB_TOKEN }}
